project:
  name: "weather-web"
  api_version: 1

clients:
  weather:
    api_key: ${env:WEATHER_API_KEY}
    host: "api.openweathermap.org"
    secret_key: ""
    prefix: "/data/2.5"

  geocoder:
    api_key: ${env:GEOCODER_API_KEY}
    secret_key: ""
    host: "geocode-maps.yandex.ru"
    prefix: "/1.x"
